version: "3.8"

services:
  caddy:
    container_name: panda-wiki-caddy
    restart: always
    image: chaitin-registry.cn-hangzhou.cr.aliyuncs.com/chaitin/panda-wiki-caddy:2.10-alpine
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/caddy/caddy_config:/config
      - ./data/caddy/caddy_data:/data
      - ./data/caddy/run:/var/run/caddy
    environment:
      - CADDY_ADMIN=tcp://localhost:2019
    network_mode: host
    command: ["caddy", "run", "--config", "/config/Caddyfile", "--adapter", "caddyfile"]

networks:
  panda-wiki:
    ipam:
      driver: default
      config:
        - subnet: "169.254.15.0/24"
