#!/usr/bin/env bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# 使用当前默认的 Node.js 版本
nvm use default 2>/dev/null || nvm use v20.17.0 2>/dev/null

cd web
pnpm exec lint-staged
